# Generated by Django 5.1.4 on 2024-12-22 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_files_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
