# Generated by Django 5.1.4 on 2024-12-22 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driveaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driveaccess'),
        ),
    ]
