# Generated by Django 5.1.4 on 2024-12-22 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveaccess',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='driveaccess',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_access_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
