# Generated by Django 5.1.4 on 2024-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encryption_iv',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='file',
            name='encryption_tag',
            field=models.BinaryField(default=b''),
        ),
    ]
