# Generated by Django 5.1.4 on 2024-12-20 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_shareablefilelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablefilelink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
